food/urls.py
from django.urls import path
from . import views

app_name = "food"
urlpatterns = [
    # path("", views.index, name="index"),
    # path("<int:item_id>", views.detail, name="detail"),
    path("", views.IndexClassView.as_view(), name="index"),
    path("<int:pk>", views.FoodDetail.as_view(), name="detail"),
    path("add", views.CreateItem.as_view(), name="create_item"),
    path("update/<int:item_id>", views.update_item, name="update_item"),
    path("delete/<int:item_id>", views.delete_item, name="delete_item"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("food/", include("food.urls")),
    path("register/", user_views.register, name="register"),
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="users/login.html"),
        name="login",
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(template_name="users/logout.html"),
        name="logout",
    ),
    path("profile/", user_views.profileview, name="profile"),
]

urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = "users"
urlpatterns = [
    # path("register", views.register, name="register"),
]

food/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


# Create your models here.
class Item(models.Model):
    def __str__(self):
        return self.item_name

    user_name = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    item_name = models.CharField(max_length=200)
    item_description = models.CharField(max_length=200)
    item_price = models.IntegerField()
    item_image = models.CharField(
        max_length=500,
        default="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT6-g6RtuMHoRdlcBwoNSO-TENKF_GBxzZntIQ_BJD2&s",
    )

    def get_absolute_url(self):
        return reverse("food:detail", kwargs={"pk": self.pk})

users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default="profilepic.jpg", upload_to="profile_pictures")
    location = models.CharField(max_length=200)

    def __str__(self):
        return self.user.username

food/forms.py
from django import forms
from .models import Item


class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = "__all__"

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class registerForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

food/views.py
from django.shortcuts import render, redirect
from django.test import TestCase
from django.http import HttpResponse
from .models import Item
from .forms import ItemForm
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView


# Create your tests here.
def index(request):
    item_list = Item.objects.all()
    context = {"item_list": item_list}
    return render(request, "food/index.html", context)


class IndexClassView(ListView):
    model = Item
    template_name = "food/index.html"
    context_object_name = "item_list"


def detail(request, item_id):
    item = Item.objects.get(pk=item_id)
    context = {"item": item}
    return render(request, "food/detail.html", context)


class FoodDetail(DetailView):
    model = Item
    template_name = "food/detail.html"


def create_item(request):
    form = ItemForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect("food:index")

    context = {"form": form}
    return render(request, "food/item_form.html", context)


# Class based view to create item


class CreateItem(CreateView):
    model = Item
    fields = ["item_name", "item_description", "item_price", "item_image"]
    template_name = "food/item_form.html"

    def form_valid(self, form):
        form.instance.user_name = self.request.user
        return super().form_valid(form)


def update_item(request, item_id):
    item = Item.objects.get(id=item_id)
    form = ItemForm(request.POST or None, instance=item)
    if form.is_valid():
        form.save()
        return redirect("food:index")

    context = {"form": form, "item": item}
    return render(request, "food/item_form.html", context)


def delete_item(request, item_id):
    item = Item.objects.get(id=item_id)
    if request.method == "POST":
        item.delete()
        return redirect("food:index")
    context = {"item": item}
    return render(request, "food/delete_item.html", context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import registerForm


# Create your views here.
def register(request):
    if request.method == "POST":
        form = registerForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            messages.success(
                request, f"Welcome {username}, your account has been created."
            )
            form.save()
            return redirect("login")
    else:
        form = registerForm()
    context = {"form": form}
    return render(request, "users/register.html", context)


@login_required
def profileview(request):
    context = {}
    return render(request, "users/profile.html", context)

food/templates/food/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>FoodApp</title>

        <link rel="stylesheet" href='{% static "food/style.css" %}' />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css"
            integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
            crossorigin="anonymous" />
    </head>

    <body>
        <nav class="navbar navbar-dark bg-dark">
            <a href="{% url 'food:index' %}" class="navbar-brand">FoodApp</a>
            <div class="navbar">

                <a class="nav-item nav-link" href=" {%  url 'food:create_item' %} ">Add Item</a>
                <a class="nav-item nav-link" href="#">Delete Item</a>
                <a class="nav-item nav-link" href="#">View Item</a>
                {% if user.is_authenticated %}
                <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
                <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>
                {% else %}
                <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                {% endif %}


            </div>
        </nav>
        <div class="container">
            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-{{message.tag}}">
                {{message}}
            </div>
            {% endfor %}
            {%endif %}
            {% block body %} {% endblock body %}
        </div>
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
            integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
            crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js"
            integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
            crossorigin="anonymous"></script>
    </body>

</html>

food/templates/food/delete_item.html
{% extends "food/base.html" %} {% block body %}
<form action='{% url "food:delete_item" item.id %}' method="POST">
    {% csrf_token %} {{form}}
    <h2>Are you sure to delete {{item.item_name}}</h2>
    <button type="submit" class="btn btn-danger">Delete Item</button>
</form>
{% endblock body %}

food/templates/food/detail.html
{% extends "food/base.html" %} {% block body %}

<div class="row">
  <div class="col-md-6">
    <img src="{{object.item_image}}" alt="" height="300px" class="card" />
  </div>
  <div class="col-md-6">
    <h3>{{object.item_name}}</h3>
    <h5>{{object.item_description}}</h5>
    <h6>${{object.item_price}}</h6>
    <a href="{% url 'food:delete_item' object.id %}" class="btn btn-danger">Delete</a>
  </div>
</div>
{% endblock body %}

food/templates/food/index.html
{% extends "food/base.html" %} {% block body %}
<h1>This is a template</h1>
<ul>
  {% for item in item_list %}

  <div class="row">
    <div class="col-md-3 offset-md-2">
      <img src="{{item.item_image}}" alt="" height="150px" class="card">
    </div>
    <div class="col-md-4">
      <h3>{{item.item_name}}</h3>
      <h5>{{item.item_description}}</h5>
      <h6>${{item.item_price}}</h6>
      <p>{{item.user_name}}</p>
    </div>
    <div class="col-md-2">
      <a href="{% url 'food:update_item' item.id %}" class="btn btn-primary">Update</a>
      <a href="{% url 'food:detail' item.id %}" class="btn btn-success">Details</a>
    </div>
  </div>

  {% endfor %}
</ul>
{% endblock body %}

food/templates/food/item_form.html
{% extends "food/base.html" %} {% block body %}
<form action="{% url "food:create_item" %}" method="POST">
  {% csrf_token %} {{form}}
  <button type="submit">Add Item</button>
</form>
{% endblock body %}

users/templates/users/login.html
<form method="POST" action="#">
    {% csrf_token %} {{form}}
    <button type="submit">Login</button>
</form>

users/templates/users/logout.html
<h1>You have been logged out</h1>

users/templates/users/profile.html
<h1>{{user.username}}</h1>
<img src="{{user.profile.image.url}}" width="50px" alt="">

users/templates/users/register.html
<form method="POST" action="#">
  {% csrf_token %} {{form}}
  <button type="submit">Register</button>
</form>